[package]
name = "crypt"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { workspace = true, features = ["derive"] }
rand = { workspace = true }
rand_chacha = { workspace = true }
argon2 = { workspace = true }
aes = { workspace = true }
ctr = { workspace = true }
zeroize = { workspace = true }
sha2 = { workspace = true }
